import os
from dotenv import load_dotenv
from dataclasses import dataclass
from typing import List

load_dotenv()

@dataclass
class MQTTConfig:
    """MQTT Broker configuration"""
    broker_host: str = os.getenv('MQTT_BROKER_HOST', 'localhost')
    broker_port: int = int(os.getenv('MQTT_BROKER_PORT', '1883'))
    topic_prefix: str = os.getenv('MQTT_TOPIC_PREFIX', 'factory/machines')
    client_id: str = os.getenv('MQTT_CLIENT_ID', 'iot-simulator')
    keepalive: int = 60

@dataclass
class SimulationConfig:
    """Simulation parameters"""
    interval_seconds: int = int(os.getenv('SIMULATION_INTERVAL_SECONDS', '5'))
    machine_count: int = int(os.getenv('MACHINE_COUNT', '5'))
    machine_id_prefix: str = os.getenv('MACHINE_ID_PREFIX', 'MACHINE')
    
    # Machine operational parameters
    temperature_min: float = 20.0
    temperature_max: float = 80.0
    temperature_critical: float = 75.0
    
    speed_min: int = 800
    speed_max: int = 1200
    speed_optimal: int = 1000
    
    # State probabilities
    running_probability: float = 0.8
    idle_probability: float = 0.15
    maintenance_probability: float = 0.05
    
    # Alarm probability (higher when temperature is critical)
    alarm_base_probability: float = 0.1
    alarm_critical_probability: float = 0.6

@dataclass
class MachineState:
    """Represents the current state of a machine"""
    machine_id: str
    temperature: float
    speed: int
    state: str  # RUNNING, IDLE, MAINTENANCE
    alarm: bool
    oee: float
    last_maintenance: str
    operator_name: str
    shift: str
    production_count: int

def load_config():
    """Load configuration from YAML file"""
    try:
        with open('config.yaml', 'r') as f:
            config_data = yaml.safe_load(f)
        
        mqtt_config = MQTTConfig(**config_data.get('mqtt', {}))
        sim_config = SimulationConfig(**config_data.get('simulation', {}))
        
        return mqtt_config, sim_config
    except FileNotFoundError:
        # Use default values if config file not found
        return MQTTConfig(), SimulationConfig()