apiVersion: 1

datasources:
  - name: PostgreSQL IoT Analytics
    type: postgres
    access: proxy
    url: postgres:5432
    database: iot_analytics
    user: iot_user
    secureJsonData:
      password: iot_password
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true